### ISSUE TITLE
Add "Live feed snippet code" field to bot

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/Farmbot-Web-API#175]
Right now, the live feed is hard coded to stream the bot feed in @roryaronson 's front yard, but this will need to change before launch,

It seems like different users are going to host their live feeds in different ways. Since we don't support it natively, it might be better to give the user a field to paste in their own live feed code snippet (however they chose to implement it is up to them- we can suggest a few solutions also). This would be a very easy to implement solution on the backend.

**Comment by roryaronson** [comment]
+1, I think this will be useful for the birds eye view camera, or whatever other views the user wants. 

As a second issue, I'd like to get an onbaord camera that can more closely see the action. This camera would be hooked up to the main pi and hopefully be supported out of the box
