### ISSUE TITLE
Circular Reference from activesupport gem.

### ISSUE THREAD

**Issue by elbow-jason** [FarmBot/Farmbot-Web-API#192]
```
home/elbow/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.0/lib/active_support/values/time_zone.rb:285: warning: circular argument reference - now
```
I'm almost positive this should be an issue on activesupport. If so, let me know.

**Comment by RickCarlino** [comment]
Eh, that happens on a lot of projects and has been relatively benign in my experience. Never got around to fixing that one, but probably should.
