### ISSUE TITLE
Unforeseen Workflow: New Planting Area.

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/Farmbot-Web-API#228]
# Scenario

 * User has initially set up device
 * User adds a device
 * User navigates to designer page

# Problem

 * The designer needs a `PlantingArea` to work off of
 * Since the device has been newly added, `Device.planting_area` is `nil`

# Possible Solution

 * Make mockups that show this workflow
 * I can add the functionality once idea is agreed upon.

**Comment by roryaronson** [comment]
What if we just don't render a planting area at all. This would prevent the user from dragging plants into the view.

We can show an alert that says "You must specify your planting area's size before designing your garden. Go to the device page to calibrate your FarmBot and automatically set your planting area, or manually enter a size"
