### ISSUE TITLE
JS_FILE_URL Environment Variable

### ISSUE THREAD

**Issue by clubleveljoe** [FarmBot/Farmbot-Web-API#254]
This is popping up as an error in my routes. I assume this is how the Node.js front-end is tied in, but I can't find anything in the documentation about its configuration.

**Comment by RickCarlino** [comment]
Hey Joe-

I'm on the road right now so I won't be able to investigate for a few days. I will take a look here shortly and update docs accordingly. Thanks for the heads up.

**Comment by RickCarlino** [comment]
Great question. Thanks for bringing it to my attention. It looks like I didn't add this one to the documentation.

`JS_FILE_URL` is a URL pointing to the [Farmbot Frontend](https://github.com/FarmBot/farmbot-web-frontend) `bundle.js` file you want to use. This allows you to run one version of the API with a different version of the frontend.

`JS_FILE_URL` is what gets injected into the `<script>` tag when the user visits `/app`. 


Thanks again. Will merge shortly and autoclose when that happens.
