### ISSUE TITLE
Connect mysql error !

### ISSUE THREAD

**Issue by airlinepilot** [FarmBot/Farmbot-Web-API#272]
when i created account on my server, i get it. how to config mysql on my server ? 
`
Started POST "/api/users" for 115.79.56.92 at 2016-09-20 17:06:36 +0700
Started POST "/api/users" for 115.79.56.92 at 2016-09-20 17:06:36 +0700

Mysql::Error (Access denied for user 'root'@'localhost' (using password: YES)):
  activerecord (4.2.7) lib/active_record/connection_adapters/mysql_adapter.rb:456:in `real_connect'
  activerecord (4.2.7) lib/active_record/connection_adapters/mysql_adapter.rb:456:in `connect'
  activerecord (4.2.7) lib/active_record/connection_adapters/mysql_adapter.rb:108:in `initialize'
  activerecord (4.2.7) lib/active_record/connection_adapters/mysql_adapter.rb:36:in `new'
  activerecord (4.2.7) lib/active_record/connection_adapters/mysql_adapter.rb:36:in `mysql_connection'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
  /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
`

**Comment by RickCarlino** [comment]
@airlinepilot Thanks for the report. We recently switched from MongoDB to MySQL

Try running these commands and restarting the server:

```

rake db:create:all
rake db:migrate

```
Most likely, the error is caused by having an uninitialized database.
Please let me know if that works and I can update the docs accordingly. Thanks.

**Comment by jeffslofish** [comment]
I also get a mysql error. I tried running the rake commands  you gave, but that didn't help. Here is my error message:


Mysql::Error (Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)):
  activerecord (4.2.7) lib/active_record/connection_adapters/mysql_adapter.rb:456:in `real_connect'
  activerecord (4.2.7) lib/active_record/connection_adapters/mysql_adapter.rb:456:in `connect'
  activerecord (4.2.7) lib/active_record/connection_adapters/mysql_adapter.rb:108:in `initialize'
  activerecord (4.2.7) lib/active_record/connection_adapters/mysql_adapter.rb:36:in `new'
  activerecord (4.2.7) lib/active_record/connection_adapters/mysql_adapter.rb:36:in `mysql_connection'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
  /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
  /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
  activerecord (4.2.7) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  activerecord (4.2.7) lib/active_record/connection_handling.rb:87:in `connection'
  activerecord (4.2.7) lib/active_record/query_cache.rb:51:in `restore_query_cache_settings'
  activerecord (4.2.7) lib/active_record/query_cache.rb:43:in `rescue in call'
  activerecord (4.2.7) lib/active_record/query_cache.rb:31:in `call'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7) lib/rails/engine.rb:518:in `call'
  railties (4.2.7) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.3ms)
  Rendered /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.3ms)
  Rendered /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.1ms)
  Rendered /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.1ms)
  Rendered /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (68.4ms)
  Rendered /Users/jeff/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (68.4ms)

**Comment by RickCarlino** [comment]
@jeffslofish Can you give this fix a try? http://stackoverflow.com/a/5499151/1064917

If it works, could you please submit a pull request? Either way, please let me know how it goes.

**Comment by airlinepilot** [comment]
I change pass of  mysql in file config/database.yml then I tried running the rake commands you gave. I success! thanks

**Comment by RickCarlino** [comment]
@airlinepilot Great!

**Comment by jeffslofish** [comment]
I tried the fix from stackoverflow, but now I get this:

Mysql::Error (Can't connect to MySQL server on '127.0.0.1' (61)):

**Comment by RickCarlino** [comment]
Did you install MySQL on your machine already?

**Comment by jeffslofish** [comment]
I do have MAMP, but it isn't running at the moment. I tried to use it for the MySQL server at one point but that didn't work either. Is a mysql server build in to the setup, or do I have to supply my own?

**Comment by airlinepilot** [comment]
but i do not connect Farmot Raspicontroler to my server. I get an error like this. 
`Setup is complete! You may now run `ruby farmbot.rb` to start the bot.
Want to run `ruby farmbot.rb` now?
y

Connecting...
/usr/local/rvm/gems/ruby-2.3.1/gems/farmbot-resource-0.6.0/lib/resources/abstract_resource.rb:31:in `fetch_no': undefined method `url' for #<Errno::ECONNREFUSED:0xebcef0> (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.3.1/gems/farmbot-resource-0.6.0/lib/resources/abstract_resource.rb:23:in `block in fetch'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/farmbot-resource-0.6.0/lib/http/bad_http_resp.rb:3:in `no'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/farmbot-resource-0.6.0/lib/resources/abstract_resource.rb:23:in `fetch'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/farmbot-resource-0.6.0/lib/resources/abstract_resource.rb:41:in `all'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/farmbot-resource-0.6.0/lib/resources/device.rb:9:in `current'
	from /var/www/farmbot-raspberry-pi-controller/lib/farmbot-pi.rb:21:in `initialize'
	from farmbot.rb:5:in `new'
	from farmbot.rb:5:in `<top (required)>'
	from setup.rb:62:in `load'
	from setup.rb:62:in `<main>'
`

**Comment by RickCarlino** [comment]
@airlinepilot This issue is not related to the API- please raise an issue on the [Raspberry Pi Controller repo by clicking here.](https://github.com/FarmBot/farmbot-raspberry-pi-controller/issues/new) This will help others find the issue when they hit the same problem.

**Comment by RickCarlino** [comment]
@jeffslofish Rails applications do not install or start MySQL, but they do require it to run.

Please try running this:

```
mysqladmin -umysql ping
```

If MySQL is running, it will say `mysqld is alive`. If it is not online, you will need to install / start the MySQL server.

**Comment by jeffslofish** [comment]
Yes, I didn't have mysql installed or started. It wasn't clear from the docs that I needed to do that. Should I add that step to a pull request?

**Comment by RickCarlino** [comment]
@jeffslofish I would really appreciate that. Thanks for the help!

If you find a good tutorial from the MySQL or MariaDB site, feel free to link it in.
