### ISSUE TITLE
Connection problems arise when the creation of users

### ISSUE THREAD

**Issue by linqingfeng** [FarmBot/Farmbot-Web-API#292]
Hi,

Connection problems arise when the creation of users, how to solve?

![image](https://cloud.githubusercontent.com/assets/6023566/20296645/08e2900e-ab47-11e6-82f6-d609ce7addac.png)

![image](https://cloud.githubusercontent.com/assets/6023566/20296695/51097a5a-ab47-11e6-86e7-1842d2832121.png)

Thank you very much.

**Comment by RickCarlino** [comment]
@linqingfeng Thanks for the report. Can you try this when you see the error?

1. Open the Javascript console. `ctrl` + `shift` + `j` on windows.
2. Copy/paste and red messages you see.
3. Go into the `network` panel and see if there are any red network requests.

Thanks!

**Comment by linqingfeng** [comment]
Hi,

Find the cause of the error, because the port number of the deployment is "3000", "API_PORT" has been set to 3000 ports, but click "CREATE ACOUNT", call the api to "http://172.16.8.100/api/users" Into a "80", and now only through the firewall forced to port 80 port 3000, as follows:

`sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 3000`

Where can I set up?

**Comment by RickCarlino** [comment]
@linqingfeng Aha! That sounds like the issue. It looks like this may be a new bug, as it would send it to `:3000` previously. I will fix the issue today.

**Comment by RickCarlino** [comment]
@linqingfeng
