### ISSUE TITLE
JWT as ID Parameter

### ISSUE THREAD

**Issue by MarceloAlves** [FarmBot/Farmbot-Web-API#304]
Hi there. I was browsing around checking the `TODO`'s and came across the issue of using [JWT tokens in the URL](https://github.com/FarmBot/Farmbot-Web-API/blob/master/config/routes.rb#L29). I believe you can override the ID param by passing it a regex so that a JWT is validated. Something like:

```ruby
resources :password_resets, only: [:create, :update], id: /.*/
```

Rails tries to match anything after the first `.` as a format so this should override that and pass the entire token as the ID. I was going to clone the repo and give it a shot but still need to setup MySQL.
Thought I'd post it here for discussion.

**Comment by RickCarlino** [comment]
@MarceloAlves Thanks for finding the cause of that issue! I completely forgot about the format thing. That TODO is actually outdated now though. We put the JWT in the query string and I think we won't gain much by switching back now but I will update that TODO accordingly. Please let me know if you need any help getting set up.

**Comment by MarceloAlves** [comment]
Ah okay cool, good to hear!

**Comment by RickCarlino** [comment]
@MarceloAlves side note: I've updated stale TODO items and added documentation to most classes and modules in `/lib` and `/models`.

**Comment by MarceloAlves** [comment]
Awesome! I'll check it out 👍
