### ISSUE TITLE
Small correction

### ISSUE THREAD

**Issue by pablomat** [FarmBot/Farmbot-Web-API#306]
Point 10 in "Developer Setup"/"Setup" should point to the Farmbot-Web-API issue list not the web-frontend.

At the moment it points to : https://github.com/FarmBot/farmbot-web-frontend/issues/new?title=Installation%20Failure

**Comment by RickCarlino** [comment]
@pablomat Can you submit a pull request for this fix?

**Comment by RickCarlino** [comment]
This was probably a bad copy / paste job from one of the other README files. Good catch.

**Comment by RickCarlino** [comment]
Actually- I need to make some changes in there for a few other things. I will push an update here shortly.

**Comment by pablomat** [comment]
Ok, no rush, it was just a small remark ;). Thanks for your support.
