### ISSUE TITLE
Possible connectivity issue

### ISSUE THREAD

**Issue by pablomat** [FarmBot/Farmbot-Web-API#307]
Hi, 

I've deployed the Web-Api plus the mqtt-gateway as described in the docs, the mqtt is able to retrieve the certificate so i believe there's no communication issue between the two but from the web frontend i cannot create an account, i receive the message "Possible connectivity issues..."

I'm using the latest ubuntu server 16.04.1 x86_64 with rvm and ruby-2.3.3 / npm 4.0.5 / node 7.4.0

emilio@ubuntu:~/Farmbot-Web-API$ rails s
=> Booting Thin
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
W, [2017-01-26T07:48:32.721120 #4793]  WARN -- : [SKYLIGHT] [1.0.1] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
Thin web server (v1.7.0 codename Dunder Mifflin)
Maximum connections set to 1024
Listening on localhost:3000, CTRL+C to stop
Started GET "/api/public_key" for 127.0.0.1 at 2017-01-26 08:05:43 -0800
Processing by Api::PublicKeysController#show as JSON
  Rendering text template
  Rendered text template (0.0ms)
Completed 200 OK in 88ms (Views: 43.5ms | ActiveRecord: 0.0ms)

--
emilio@ubuntu:~/mqtt-gateway$ npm start

> farmbot-mqtt-gateway@1.1.0 start /home/emilio/mqtt-gateway
> nodemon --exec ./node_modules/.bin/ts-node -- ./app/index.ts

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `./node_modules/.bin/ts-node ./app/index.ts`
Using http://localhost:3000 as API URL
Server online

Downloaded certificate from http://localhost:3000/api/public_key

---

database.yml :

default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: farmbot_development
  pool: 5
  username: XXX
  password: XXX

development:
  database: farmbot_development
  <<: *default

test:
  database: farmbot_test
  <<: *default

production:
  database: farmbot_prod
  <<: *default

---

Thanks

**Comment by RickCarlino** [comment]
When you click the "login" button, what errors do you see in the browser's Javascript console? (CTRL+SHIFT+J)

**Comment by pablomat** [comment]
Hi Rick, 

I've managed to create a user using the API with curl and verifying the token manually too, with that user i'm able to login to the frontend without problems (specifying server url/port to 127.0.0.1:3000).

The problem arises when i try to create an account via the frontend, from the Javascript console i get the following message (might be a problem with xhr.js not using port 3000 ?)

xhr.js?14ed:160 OPTIONS http://127.0.0.1/api/users/ net::ERR_CONNECTION_REFUSED
(anonymous) @ xhr.js?14ed:160
e.exports @ xhr.js?14ed:12

util.ts?fbc3:47 DONT KNOW HOW TO HANDLE THIS ERROR MESSAGE.
s @ util.ts?fbc3:47
a @ util.ts?fbc3:36
(anonymous) @ front_page.tsx:83

util.ts?fbc3:48 Error: Network Error
    at e.exports (http://127.0.0.1:3000/dist/front_page.3d061d823e31e3eb496e.js:4:22583)
    at XMLHttpRequest.h.onerror (http://127.0.0.1:3000/dist/front_page.3d061d823e31e3eb496e.js:4:21721)config: Objectmessage: "Network Error"response: undefinedstack: "Error: Network Error↵    at e.exports (http://127.0.0.1:3000/dist/front_page.3d061d823e31e3eb496e.js:4:22583)↵    at XMLHttpRequest.h.onerror (http://127.0.0.1:3000/dist/front_page.3d061d823e31e3eb496e.js:4:21721)"__proto__: Object

Thanks

**Comment by RickCarlino** [comment]
@pablomat This was an edge case that I have (hopefully) just fixed. We do most of our local dev work on `localhost` rather than `127.0.0.1`. Please let me know if it works now.

**Comment by pablomat** [comment]
Thanks, it works now ;)
