### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by vindekator** [FarmBot/Farmbot-Web-API#308]
Hi.  I'm not that familiar with working from the command line as I've always installed GUIs when possible.  I'm working from Debian 8.6 and am not sure what I should be doing with line 8 of the install: "MQTT_HOST=your_mqtt_server_domain rails s".  Is this an environment variable to be set up?  A rails command?

I installed ruby with rbenv.

**Comment by RickCarlino** [comment]
@vindekator Although Ubuntu is a Debian based distro (and are similar in many ways), I would highly recommend that you use Ubuntu Server 16.10 as we do not officially support other distros. You might not hit any issues with Debian, but that being said, we don't test against any of the issues that arise on other distributions.

As far as ENV variables go, they are a standard part of any Unix based operating system and are a common way of setting configuration on servers. Here is a [tutorial on ENV variables](https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps).

**Comment by vindekator** [comment]
Thanks for the heads up.  So it seems the answer is yes, it's an env variable.  I've knocked out most of the bumps on the Debian install but I will give Ubuntu a shot.
