### ISSUE TITLE
Need an opensource distributed database and search engine ?

### ISSUE THREAD

**Issue by vroyer** [FarmBot/Farmbot-Web-API#309]
Hi,

I'm the author of [Elassandra](https://github.com/strapdata/elassandra) , an opensource project that merge the Apache Cassandra database and a famous search engine "Elasticsearch". It's well suited to build a worldwide database with cross-datacenters replication coupled with search, geo-search features, and realtime reporting. It would be adapted to build a social network or a species inventory... I would be pleased to contribute to your awesome project !
Thanks.

**Comment by RickCarlino** [comment]
Hi @vroyer,

We just switched to Postgres from Mongo less than 6 months ago and it's been working well for us. We don't have any full text search use cases at the moment, either. I'll take a look and let you know if our situation ever changes. Thanks for the heads up.
