### ISSUE TITLE
How to modify the APP for it to handle different interchangeable Garden bed ?

### ISSUE THREAD

**Issue by dumielle** [FarmBot/Farmbot-Web-API#310]
Hi,

My name is Jean and I'm new here so please forgive me if I'm posting on the wrong place or asking a dumb or already resolved question > 

We are testing here (in Portugal) a mechanical solution for having Farmbot machine firmely anchored into the ground, with in the middle a sliding mechanism so to be able to swop gardening beds without having to move the machine. 

Would anyone know how to modify the software for it to handle let say 3 or more different beds with different crops there ?

Looking forward to read you

Have all a great day

JEAN

**Comment by RickCarlino** [comment]
Hi @dumielle ,

That sounds like an amazing project. I love the idea, but unfortunately this is not a use case we test against.

One possible solution would be to keep 3 separate SD Cards and 3 corresponding FarmBot Web App accounts. You can keep the same email address for each of the acounts by using `+` symbols in your account. Example:

```
my_farmbot+bed_1@gmail.com
my_farmbot+bed_2@gmail.com
my_farmbot+bed_3@gmail.com
```

You would need to then:

 0. Power the device off
 0. Insert a different SD card.
 0. Power back on.
 0. Log in to the other account.

@ConnorRigby : I would be interested to hear your opinion on this matter.

Please let us know how this works. I know it's not the most convenient setup, but it may get the job done for now.
