### ISSUE TITLE
SMTP Problem

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/Farmbot-Web-API#311]
Please help configure SMTP
I use smtp server smtp.yandex.ru
this server only ssl port use 465
may be use ssl://smtp.yandex.ru or not
Please help me this

**Comment by Daniil145** [comment]
Or off activation with email

**Comment by RickCarlino** [comment]
@Daniil145 Disabling email verification won't be a quick fix for us, unfortunately.

You can run this snippet to verify all users in one command:

```
User.update_all(verified_at: Time.now, verification_token: nil, agreed_to_terms_at: Time.now)
```

I've also added a new ENV var- `ENV["SMTP_PORT"]`. The ENV var will allow you to set the port of your SMTP server. Please let me know if that works.

Please let me know if that works for you.

**Comment by Daniil145** [comment]
where to run this code? 
User.update_all(verified_at: Time.now, verification_token: nil, agreed_to_terms_at: Time.now)

**Comment by Daniil145** [comment]
Prompt service mail which certainly works with IPA. With my I did not get.

**Comment by RickCarlino** [comment]
> where to run this code?
 > User.update_all(verified_at: Time.now, verification_token: nil, agreed_to_terms_at: Time.now)
@Daniil145 You would run this from the Rails console. `heroku run rails console`.

**Comment by RickCarlino** [comment]
> Prompt service mail which certainly works with API. With my I did not get.

Please take a look at the logs using `heroku logs --tail`. Try to register for an account or do something that requires email. Look for errors related to delivery.

Also, you can set the ENV vars locally and try it on your machine first to make sure the email server is not the problem.
