### ISSUE TITLE
Deployment use Heroku

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/Farmbot-Web-API#312]
Its now i use localhost its work good.

but I would like to start using heroku
I use this first.

after migrate base on heroku
i use heroku ps:scale web=1 and applet dont running, crash.

I think that there are some nuances to deploy to heroku.

May be you help me, I would like to receive detailed information for heroku deploy. And go toe to toe with you. I try to run the app for 3 days and I can not understand what I'm doing wrong.
Thx for read

**Comment by RickCarlino** [comment]
You can view logs with

```
heroku logs --app=farmbot-staging --tail
```

This will give you a better idea of what is wrong.

Did you set all the ENV variables and migrate your database? `heroku run rake db:setup` might help.
