### ISSUE TITLE
Question about a TODO

### ISSUE THREAD

**Issue by issamsham** [FarmBot/Farmbot-Web-API#317]
Hello,
I have installed and configured my own local server successfully but I don't know what should I to fill out in Email tap in Raspberry pi3 configurator page, 
Please find the attached images below,
<img width="1280" alt="screen shot 2017-03-17 at 1 57 05 pm" src="https://cloud.githubusercontent.com/assets/18642473/24044096/f82b37ec-0b19-11e7-9a29-a4b32687e670.png">
<img width="1280" alt="screen shot 2017-03-17 at 2 00 23 pm" src="https://cloud.githubusercontent.com/assets/18642473/24044114/1616eed6-0b1a-11e7-89e7-40970b2d6fd3.png">

Thank you!

**Comment by RickCarlino** [comment]
A few things:

 * Your API host is `localhost` in the configuration window. You must change this to the IP address or domain name of the server. If you set any of the [env variables](https://github.com/FarmBot/Farmbot-Web-API#config-settings-important) to `localhost`, your bot will not function.
 * You are running an old version of FarmBot OS, judging by the UI of the configuration window. Please re-flash the SD card with the latest release of FarmBot OS.
 * You will need to run `./install_frontend.sh` if you want to use the app on a local network. The step is optional if you run your server on a server with SSL enabled, but your server is not using SSL (`http://` on a local network).

It seems that most users are not running servers on a public IP, so I will update the documentation to remove the word "optional" from the `./install_frontend.sh` part of the instructions. I think this will clear up some confusion.

**Comment by issamsham** [comment]
Hello,
During NPM installation, I have received many errors, please check out the attached image file 
<img width="1280" alt="screen shot 2017-03-27 at 1 47 53 pm" src="https://cloud.githubusercontent.com/assets/18642473/24450405/14a1031a-147b-11e7-829b-415ec3bf0180.png">

**Comment by RickCarlino** [comment]
@issamsham In the future, please start new issues in a new discussion thread. This helps other users with similar problems find answers via search.

To answer your question though, it looks like `webpack-dev-server` did not install correctly. Try running `npm install` in again. If you see any error messages, please show me them in a new discussion thread.
