### ISSUE TITLE
Installation Failure - rake role <username> does not exist

### ISSUE THREAD

**Issue by carlosen14** [FarmBot/Farmbot-Web-API#318]
Downloaded the master branch version, in step **6.- rake db:create:all db:migrate db:seed** I got an error, but before that, i have to do step 5 like this `ALTER USER "user" WITH SUPERUSER;` with comas because it was showing a `syntax error at or near "user"`, but got step 5. 

At step 6, it throws an error showing `FATAL: role "farmbot" does not exist  - rake aborted`

That is my username "farmbot". Does it have anything to do with my login username? Do I have to create a new username named "user" to get it work?

**Comment by gabrielburnworth** [comment]
A username such as `farmbot` should work fine. What response do you get after `ALTER USER farmbot WITH SUPERUSER;`?

**Comment by RickCarlino** [comment]
@carlosen14 Did that help? This is a [pretty common issue when setting](http://stackoverflow.com/a/23841599/1064917) when setting a Rails project up for the first time, but it should go away once you have a user by that name setup. Please let us know if the steps above don't help and I can reopen the issue.

**Comment by carlosen14** [comment]
Sorry for being late..

When I said my username was "farmbot" I was referring to my ubuntu username. postgresql username is "user"

I ran this command `rake db:create:all db:migrate db:seed --trace`

and got this trace.

> farmbot@farmbot-VirtualBox:~/proyecto/Farmbot-Web-API$ rake db:create:all db:migrate db:seed --trace
> ** Invoke db:create:all (first_time)
> ** Invoke db:load_config (first_time)
> ** Execute db:load_config
> ** Execute db:create:all
> FATAL:  role "farmbot" does not exist
> Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"farmbot_development", "pool"=>5}
> rake aborted!
> ActiveRecord::NoDatabaseError: FATAL:  role "farmbot" does not exist
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `rescue in connect'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `connect'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:721:in `new_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:765:in `checkout_new_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:744:in `try_to_checkout_new_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:705:in `acquire_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:91:in `connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/postgresql_database_tasks.rb:6:in `connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/postgresql_database_tasks.rb:15:in `create'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:109:in `create'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:121:in `block in create_all'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:301:in `block in each_local_configuration'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:297:in `each_value'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:297:in `each_local_configuration'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:121:in `create_all'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:21:in `block (3 levels) in <top (required)>'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
> /home/farmbot/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
> /home/farmbot/.rvm/gems/ruby-2.3.3/bin/rake:22:in `load'
> /home/farmbot/.rvm/gems/ruby-2.3.3/bin/rake:22:in `<main>'
> /home/farmbot/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
> /home/farmbot/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
> PG::ConnectionBad: FATAL:  role "farmbot" does not exist
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `initialize'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `new'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `connect'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:721:in `new_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:765:in `checkout_new_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:744:in `try_to_checkout_new_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:705:in `acquire_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:91:in `connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/postgresql_database_tasks.rb:6:in `connection'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/postgresql_database_tasks.rb:15:in `create'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:109:in `create'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:121:in `block in create_all'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:301:in `block in each_local_configuration'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:297:in `each_value'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:297:in `each_local_configuration'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:121:in `create_all'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:21:in `block (3 levels) in <top (required)>'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
> /home/farmbot/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
> /home/farmbot/.rvm/gems/ruby-2.3.3/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
> /home/farmbot/.rvm/gems/ruby-2.3.3/bin/rake:22:in `load'
> /home/farmbot/.rvm/gems/ruby-2.3.3/bin/rake:22:in `<main>'
> /home/farmbot/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
> /home/farmbot/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
> Tasks: TOP => db:create:all

This is the postgresql user info

postgres=# ALTER USER farmbot WITH SUPERUSER;
ALTER ROLE
postgres=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 farmbot   | Superuser                                                  | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 user      | Superuser                                                  | {}

Just to mention that doing that adding farmbot username to postgresql solve this problem. I am thinking that postgresql takes the ubuntu username to expect use the same username. 

thanks for the help.

**Comment by gazziandres** [comment]
THX THIS HELPS ME A LOT
