### ISSUE TITLE
Setting Up Own Web API

### ISSUE THREAD

**Issue by phillip-shvartsman** [FarmBot/Farmbot-Web-API#320]
Hello,
I’m creating a version of your farmbot as part of a project for my school. We plan to use the Raspberry PI and Arduino software on the github, and are writing our own Web server in Node.js. The web interface will take commands from anyone with the webaddress, and will act as sort of a community garden. Imitating this: 
http://goldberg.berkeley.edu/garden/Ars/

I understand that the web interface needs to send MQTT through a broker to the Pi. Is there a place where the MQTT requests are listed and what they correspond to so that we can mimic them on our web server.

Thank you,
Phillip Shvartsman

**Comment by RickCarlino** [comment]
@phillip-shvartsman That sounds like a fun project! We would love to help you.

If you wish to control a FarmBot with Javascript and not use the frontend, then [FarmbotJS](https://github.com/RickCarlino/farmbot-js) is a good starting point. It should run fine in a NodeJS environment, although we have only tested it in a browser, since that is where we use it today.

In regards to your question of "place where the MQTT requests are listed" you have two options:

 1. Use FarmbotJS instance methods such as `bot.moveRelative()`, `bot.powerOff()`, `bot.writePin()` etc..
 2. Publish a JSON object by hand to MQTT. If your bot's ID was `42`, you would publish a JSON object to the channel `bot/device_42/from_clients` (notice the 42). These objects are written in an internal data interchange format called "Celery Script". It's JSON with special formatting. You can see the Typescript interfaces that describe those objects [here](https://github.com/RickCarlino/farmbot-js/blob/master/src/corpus.ts).

Here's a real world example of Celery Script fetching all of the device state:

```
// SENT TO `bot/device_163/from_clients`
{
  // "kind" is the message type. "rpc_request", "read_status", "move_relative", etc...
  "kind": "rpc_request",
  "args": {
   // Every celery script command has a random "label" so response can be demultiplexed
    "label": "7c3074d5-6685-4ded-ad0f-b7301f5f590c"
  },
  // a body is a list of Celery Script nodes nested inside of a parent.
  // This particular node is an RPC call that only nests one command ("read status")
  "body": [
    {
      "kind": "read_status",
      "args": {}
    }
  ]
}

```

If you would prefer not to use our wrapper library (eg, if it is purely for educational purposes), I can write some celery script documentation. It is undocumented at the moment for the simple reason that no one has asked for documentation yet. Let us know how we can help.

**Comment by phillip-shvartsman** [comment]
@RickCarlino Thank you for the quick response! and thank you for pointing me to FarmbotJS! I think we will use that for the project. I was reading through the accepted commands and they seem self-explanatory except for a few. I was wondering what is the format of the commandObject in send(commandObject), and what the syncSequence command does.
Thank you again,
Phillip Shvartsman

**Comment by RickCarlino** [comment]
@phillip-shvartsman Good question. I will add documentation to the library source today. If you use an editor that supports inline documentation (such as VS Code or Atom), the docs should show up as hints. 

To answer your questions though:

 * The command objects are formatted as Celery Script nodes (mentioned above). The interfaces defined in `corpus.ts`. For instance, the `take_photo` node's structure is defined [here](https://github.com/FarmBot/farmbot-js/blob/master/src/corpus.ts#L402) on line 402.
 * The `send` command is a low level helper function that let's you send arbitrary JSON to the bot. You shouldn't need this, as all commands have helper functions already written. This eliminates the need to memorize the structure of command objects.
 * `syncSequence` was renamed to `sync` (thanks for catching the documentation issue!). a `sync` command instructs the bot to download new resources from the user's account at my.farmbot.io (or a self hosted server). If you are trying to build your own back end, this might be less useful.

Thanks for the great questions. I will let you know when the documentation is updated.

**Comment by RickCarlino** [comment]
@phillip-shvartsman I've [added documentation](https://rawgit.com/FarmBot/farmbot-js/master/doc/classes/_src_farmbot_.farmbot.html) to the project and have updated the README (there were some dperecated / irrelevant comments in there still).

If you have any more questions, please raise an issue on the FarmBotJS repo.

**Comment by phillip-shvartsman** [comment]
@RickCarlino Thank you Rick, I really appreciate it.

**Comment by RickCarlino** [comment]
@phillip-shvartsman Is FarmBotJS working out for you? Please let me know if you have any other questions.

**Comment by phillip-shvartsman** [comment]
@RickCarlino Hey Rick sorry for being silent, We're just working on the front-end while we wait for the hardware to come in. I'll try this weekend and let you know if there is any issues. While we wait, could I install the Farmbot-OS on my pi and connect it to my.farmbot.io ? Then the log in my.farmbot.io will display connections from Farmbot-JS?

**Comment by RickCarlino** [comment]
@phillip-shvartsman Yes, it is possible to flash an RPi with FarmBot OS and log in to it as if it were a "real" FarmBot. That might be a good way to get familiarized with FarmBotJS and the API, also.

**Comment by phillip-shvartsman** [comment]
@RickCarlino Hey Rick, I'm trying to use the farmbot-js package in Node.js and going off the readme. I can't use the import keyword after installing the module. I used require

var Farmbot = require('farmbot')

 instead and this was allowed. However, when I try to create a new bot with 

bot = new Farmbot({token:secret_token})

I get: Type Error : Farmbot is not a constructor. What is the correct way to use Farmbot in node? Thank you.

**Comment by phillip-shvartsman** [comment]
Do I need to make the project typescript?

**Comment by RickCarlino** [comment]
@phillip-shvartsman A couple things:

1. `import` only works if you use the latest version of node or an ES-6 transpiler like Babel or Typescript.
2. The code should actually look like this:
```
// "import" only works on newer versions of node.
var Farmbot = require("farmbot").Farmbot;
var bot = new Farmbot({token:"SECRET_TOKE_HERE!!"});
```
3. I recently started testing NodeJS setups. Like I mentioned before, although it is possible, we don't actually use NodeJS for this sort of thing in the official repos. While trying to build an example app in NodeJS ([here](https://github.com/FarmBot-Labs/FarmBot-Chat-Bot)) I noticed there were still some issues that need to be worked out. I can take a deeper look tonight.
4. You don't *need* Typescript, but you will get a lot of benefits if you do.
5. You will need to [do this](https://github.com/FarmBot/farmbot-js/issues/33) for now, to avoid some issues in Node.

**Comment by RickCarlino** [comment]
@phillip-shvartsman I will let you know when I pin down the issue. If you feel like taking a look for yourself, I believe the issue is somewhere with MQTT.js (a dependency of FarmBot JS).

**Comment by phillip-shvartsman** [comment]
@RickCarlino Yeah I got the MQTT timeout error. I'll take a look but I don't think I will be much help!

**Comment by RickCarlino** [comment]
@phillip-shvartsman :tada:  It looks like FarmBotJS `v3.9.3` has full support for NodeJS if you shim the `atob` function. Please upgrade to the latest version of FarmBotJS (3.9.3) and let me know how it works out for you. Also, let's move further discussion to the [FarmBotJS repo](https://github.com/FarmBot/farmbot-js).

Also: the `farmbot_chatbot` [example project](https://github.com/FarmBot-Labs/FarmBot-Chat-Bot) seems to work now, if you need example code. Hope this helps!

**Comment by phillip-shvartsman** [comment]
@RickCarlino Thanks rick!
