### ISSUE TITLE
White background after login

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/Farmbot-Web-API#322]
I install farmbot-api and install base and interface
login page work correctly - registration complete
after login - white background
![image](https://cloud.githubusercontent.com/assets/20598279/25092281/ab83c032-2395-11e7-9edb-0967beed9703.png)

**Comment by Daniil145** [comment]
for all my devices on google chrome

**Comment by RickCarlino** [comment]
@Daniil145 This issue was fixed a few days ago, but it looks like you are running a frontend version from `April 8`. Please try to `./install_frontend.sh` again.

**Comment by RickCarlino** [comment]
Closing issue for now. Please let me know if that does not work and I can re-open.

**Comment by Daniil145** [comment]
Hi, @RickCarlino I install fresh today. and this error again(

**Comment by Daniil145** [comment]
I dont install ImageMagic pls add to Readme)

**Comment by Daniil145** [comment]
Worked)

**Comment by RickCarlino** [comment]
@Daniil145 Great to hear. Will update the README in a bit.

**Comment by RickCarlino** [comment]
README is updated :+1: Thanks for letting me know.
