### ISSUE TITLE
ENV var for disabling registration confirm emails?

### ISSUE THREAD

**Issue by creimers** [FarmBot/Farmbot-Web-API#326]
Is there a way to say "I'm running the API service locally/on premise and I don't want/need to send out confirmation emails after user registration"?

**Comment by RickCarlino** [comment]
@creimers I've just added `NO_EMAILS` env var. Please let me know if that helps. Thanks!

**Comment by creimers** [comment]
I checked out the latest version of the master branch (17a6afb862833792df2), and now the registration does not seem to work for me anymore.

Registering via the frontend form gives me a 500:

```
ActiveModel::UnknownAttributeError (unknown attribute 'password' for User.):
```

Additionally, here's the test output:

```
WARNING: Skipping key "FW_UPDATE_SERVER". Already set in ENV.
WARNING: Skipping key "OS_UPDATE_SERVER". Already set in ENV.
WARNING: Skipping key "MQTT_HOST". Already set in ENV.
WARNING: Use strings for Figaro configuration. false was converted to "false".

Randomized with seed 25565
F

Failures:

  1) Api::ImagesController#index shows only the max images allowed
     Failure/Error: let(:user) { FactoryGirl.create(:user) }

     NoMethodError:
       undefined method `password=' for #<User:0x00000007e433b8>
     # ./spec/controllers/api/images/images_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/controllers/api/images/images_spec.rb:9:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/bin/rspec:17:in `load'
     # /usr/local/bundle/bin/rspec:17:in `<main>'

Finished in 0.07003 seconds (files took 7.55 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/controllers/api/images/images_spec.rb:8 # Api::ImagesController#index shows only the max images allowed

Randomized with seed 25565

Coverage report generated for RSpec to /app/coverage. 1202 / 1860 LOC (64.62%) covered.
```

The commit I was on yesterday still works (80242de).

I'm not a rails guy, so I can't be of much help here I'm afraid...

**Comment by RickCarlino** [comment]
@creimers Could you try running `rails db:migrate` and `rake db:setup` again to play it safe? I will investigate again here in a moment. Please let me know if that does/does not fix the issue.

**Comment by creimers** [comment]
@RickCarlino `db:migrate` runs with no errors. `db:setup` tells me that the database already exists. And `db:seed` also says:

```
ActiveModel::UnknownAttributeError: unknown attribute 'password' for User.
```

I have narrowed things down: The commit introducing `NO_EMAILS` is already broken for me, not only the latest at time of writing.

**Comment by creimers** [comment]
@RickCarlino Have you also had the chance to look into this again?

**Comment by RickCarlino** [comment]
@creimers Can you try this and let me know if it yields different results?

0. Close any Rails servers or database clients that may be running.
1. Update to the latest version of the API. **A lot of things have changed in the last 24 hours**.
2. Run the commands below:
```
rm db/schema.rb
rake db:drop:all
rake db:create:all
rake db:migrate
rspec spec
```
3. (if everything passes) try loging in as `admin@admin.com`/`password123`.

**Comment by creimers** [comment]
With an all fresh db and `rm db/schema.rb` I get one failure during test:
```
$ rspec spec
WARNING: Skipping key "FW_UPDATE_SERVER". Already set in ENV.
WARNING: Skipping key "OS_UPDATE_SERVER". Already set in ENV.
WARNING: Skipping key "MQTT_HOST". Already set in ENV.
WARNING: Use strings for Figaro configuration. false was converted to "false".

Randomized with seed 49609
F

Failures:

  1) Device is associated with a user
     Failure/Error: let(:device){ FactoryGirl.create(:device, users: [FactoryGirl.create(:user)])}

     NoMethodError:
       undefined method `password=' for #<User:0x00000006090320>
     # ./spec/models/farmbot_device_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/models/farmbot_device_spec.rb:8:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/bin/rspec:17:in `load'
     # /usr/local/bundle/bin/rspec:17:in `<main>'

Finished in 0.06137 seconds (files took 7.19 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/models/farmbot_device_spec.rb:7 # Device is associated with a user

Randomized with seed 49609

Coverage report generated for RSpec to /app/coverage. 1196 / 1852 LOC (64.58%) covered.
```

**Comment by RickCarlino** [comment]
@creimers Can I see line 13 of your `schema.rb` file?

**Comment by creimers** [comment]
Line 13:
`ActiveRecord::Schema.define(version: 20170502184027) do`

**Comment by RickCarlino** [comment]
Interesting. Did you get any errors when running step 2 above?

**Comment by creimers** [comment]
The first time I ran it, I ran into some docker-compose specific kind of problem. I then killed and removed the db container and made myself a new one. Then omitted steps 3 + 4. 

When I run `rake db:drop:all` now, however, I get:

```
rake aborted!
ActiveRecord::NoEnvironmentInSchemaError:

Environment data not found in the schema. To resolve this issue, run:

        bin/rails db:environment:set RAILS_ENV=development
```

**Comment by RickCarlino** [comment]
@creimers It might be that the `farmbot_test` database exists, but rails only ran the migrations on `farmbot_development` (eg: an incomplete database where the `users` table does not yet have a `password` column).

Try the steps I've listed above from start to finish. if `db:create:all` or `db:migrate` don't succeed, the tests won't be able to run.

**Comment by RickCarlino** [comment]
@creimers Also, you can try `rails db:migrate RAILS_ENV=test` if that doesn't work.

**Comment by RickCarlino** [comment]
@creimers Any luck with the `create` and `migrate` steps?

**Comment by creimers** [comment]
Not quite. But I'm starting to think that it is related to the fact that I'm trying to do it with docker-compose and that something is not configured right there...
