### ISSUE TITLE
Rails won´t start

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/Farmbot-Web-API#327]
Hi all,

my rails does weird stuff and does not start anymore. Don't know what I changed, I only tried to connect my farmbot which did not work. I get:
`rails -s 192.168.0.38
WARNING: Use strings for Figaro configuration. 587 was converted to "587".
rails aborted!
Don't know how to build task '192.168.0.38' (see --tasks)
/home/klimbim/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/home/klimbim/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/home/klimbim/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/klimbim/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
`

Anyone any idea?

**Comment by RickCarlino** [comment]
Instead of `rails -s` try `rails s --port=0.0.0.0`.

Please let me know if there is documentation anywhere with the `-s`, as that would be a spelling error that needs to be corrected. Also, doing `--port=0.0.0.0` will bind to all ports, which will make debugging easier.

**Comment by Klimbim1** [comment]
@RickCarlino I guess you meant rails s -b 0.0.0.0 being 0.0.0.0 the ip in the local LAN; this works for me!

**Comment by RickCarlino** [comment]
@Klimbim1 Whoops! Yes, `-b` for "bind to IP".
