### ISSUE TITLE
Farm Designer

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/Farmbot-Web-API#329]
If I would like to drag and drop (leek for example) it sometimes does not show up on the right side as a plant in the field; however it shows in the left sidebar that it has been planted... o.O

**Comment by linyongzheng** [comment]
There is a known bug where if you're completely zoomed out on your "field" on the right side that the icons do not show up. If you zoom in the icons show up.

**Comment by Klimbim1** [comment]
This is not reproducable; if I zoom in an plant something it shows up; if I zoom out and plant something it only shows up in the database but not on the right side;
If I edit one of those two, it is always the graphical object which I planted in zoomed in mode; 
that does not work properly!

And moreover what is the coordinate system logic? This needs to match with farmbot in order to be used!!!!???
