### ISSUE TITLE
Install, Readme etc.

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/Farmbot-Web-API#332]
Hi all,

if I try with ruby-2.3.3 it says at `bundle install`:
`The git source `git://github.com/gogovan/delayed_job.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/gogovan/delayed_job_active_record.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Your Ruby version is 2.3.3, but your Gemfile specified 2.4.1`

If I tell him to use ruby-2.4.1:
`/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'bundler' (>= 0.a) among 17 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/myuser/.rvm/gems/ruby-2.4.1:/home/myuser.rvm/gems/ruby-2.4.1@global', execute `gem env` for more information
	from /usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/bin/bundle:22:in `<main>'`
gem env says: 
`RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.11
  - RUBY VERSION: 2.4.1 (2017-03-22 patchlevel 111) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/myuser/.rvm/gems/ruby-2.4.1
  - USER INSTALLATION DIRECTORY: /home/myuser/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /home/myuser/.rvm/rubies/ruby-2.4.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/myuser/.rvm/gems/ruby-2.4.1/bin
  - SPEC CACHE DIRECTORY: /home/myuser/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/myuser/.rvm/gems/ruby-2.4.1
     - /home/myuser/.rvm/gems/ruby-2.4.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/myuser/.rvm/gems/ruby-2.4.1/bin
     - /home/myuser/.rvm/gems/ruby-2.4.1@global/bin
     - /home/myuser/.rvm/rubies/ruby-2.4.1/bin
     - /home/myuser/.rvm/bin
     - /home/myuser/.rbenv/plugins/ruby-build/bin
     - /home/myuser/.rbenv/shims
     - /home/myuser/.rbenv/bin
     - /home/myuser/bin
     - /home/myuser/.local/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
`
Any ideas?

**Comment by RickCarlino** [comment]
The first set of warnings can be ignored. I've silenced them in the latest version on master (pushed a few moments ago).

As for the second error, run `gem install bundler` and try again.
