### ISSUE TITLE
E-Mail verification does not work

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/Farmbot-Web-API#333]
Hi all,

how can I verify a new E-Mail address in the latest version?
Even with the E-Mail: True parameter in application.yml I cannot get into the account....?

**Comment by RickCarlino** [comment]
@Klimbim1 As mentioned in the previous post, you are not running the correct version to support the `NO_EMAILS: TRUE` option. In the meantime, you can manually verify accounts in the [Rails Console](http://guides.rubyonrails.org/command_line.html#rails-console) (typing `rails c` first):

```
User.update_all(verified_at: Time.now)
```

You can also do this in one line from the command line, via the [Rails Runner](http://guides.rubyonrails.org/command_line.html#rails-runner):

```
rails runner "User.update_all(verified_at: Time.now)"
```
