### ISSUE TITLE
Error downloading data

### ISSUE THREAD

**Issue by Arduns** [FarmBot/Farmbot-Web-API#334]
when i use admin@admin.com Login !it just have menu and show :
           Error downloading data
           Please try refreshing the page.

Started GET "/app/controls" for 192.168.1.174 at 2017-06-30 12:44:22 +0800
Processing by DashboardController#index as HTML
  Parameters: {"path"=>"controls"}
  Rendering html template
  Rendered html template (0.0ms)
Completed 200 OK in 2ms (Views: 1.3ms)

**Comment by RickCarlino** [comment]
@Arduns We have made some recent changes to way the API is built in the last 24 hours. I will update the README today to reflect the changes and let you know.

Did you already run `rails db:seed`? Was the `admin@admin.com` account working previously?

**Comment by RickCarlino** [comment]
@Arduns I have updated the documentation for the new server setup. I am unsure if this is related to the issue you are facing. Please let me know if it solves the issue. Closing for now, can re-open as needed.

**Comment by Arduns** [comment]
@RickCarlino  I have find the Problem！when  i login it cloud not  take token！i have try  use the Postmen and send Authorization in header，  the API is work ！


24bd62a
Mon Jun 26 13:48:55 2017 -0500
Merge-pull-request-220-from-ConnorRigby-replace_github_releases_phase1
VM555:37 WebSocket connection to 'ws://192.168.1.215:3002/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
WrappedWebSocket @ VM555:37
localhost:3000/api/users/ Failed to load resource: net::ERR_CONNECTION_REFUSED
webpack:///./src/interceptors.ts?:46 GOT MALFORMED HTTP REJECTION?? This shouldn't happen!
responseRejected @ webpack:///./src/interceptors.ts?:46
localhost:3000/api/device/ Failed to load resource: net::ERR_CONNECTION_REFUSED
interceptors.ts:46 GOT MALFORMED HTTP REJECTION?? This shouldn't happen!
responseRejected @ interceptors.ts:46
webpack:///./~/farmbot-toastr/dist/index.js?:136 Please try refreshing the page.
exports.warning @ webpack:///./~/farmbot-toastr/dist/index.js?:136
localhost:3000/api/farm_events/ Failed to load resource: net::ERR_CONNECTION_REFUSED
webpack:///./src/interceptors.ts?:46 GOT MALFORMED HTTP REJECTION?? This shouldn't happen!
responseRejected @ webpack:///./src/interceptors.ts?:46
webpack:///./~/farmbot-toastr/dist/index.js?:136 Please try refreshing the page.
exports.warning @ webpack:///./~/farmbot-toastr/dist/index.js?:136
localhost:3000/api/images/ Failed to load resource: net::ERR_CONNECTION_REFUSED
webpack:///./src/interceptors.ts?:46 GOT MALFORMED HTTP REJECTION?? This shouldn't happen!
responseRejected @ webpack:///./src/interceptors.ts?:46
webpack:///./~/farmbot-toastr/dist/index.js?:136 Please try refreshing the page.
exports.warning @ webpack:///./~/farmbot-toastr/dist/index.js?:136
localhost:3000/api/logs/ Failed to load resource: net::ERR_CONNECTION_REFUSED
webpack:///./src/interceptors.ts?:46 GOT MALFORMED HTTP REJECTION?? This shouldn't happen!
responseRejected @ webpack:///./src/interceptors.ts?:46
webpack:///./~/farmbot-toastr/dist/index.js?:136 Please try refreshing the page.
exports.warning @ webpack:///./~/farmbot-toastr/dist/index.js?:136
localhost:3000/api/peripherals/ Failed to load resource: net::ERR_CONNECTION_REFUSED
webpack:///./src/interceptors.ts?:46 GOT MALFORMED HTTP REJECTION?? This shouldn't happen!
responseRejected @ webpack:///./src/interceptors.ts?:46
webpack:///./~/farmbot-toastr/dist/index.js?:136 Please try refreshing the page.
exports.warning @ webpack:///./~/farmbot-toastr/dist/index.js?:136
localhost:3000/api/points/ Failed to load resource: net::ERR_CONNECTION_REFUSED
webpack:///./src/interceptors.ts?:46 GOT MALFORMED HTTP REJECTION?? This shouldn't happen!
responseRejected @ webpack:///./src/interceptors.ts?:46
webpack:///./~/farmbot-toastr/dist/index.js?:136 Please try refreshing the page.
exports.warning @ webpack:///./~/farmbot-toastr/dist/index.js?:136
localhost:3000/api/regimens/ Failed to load resource: net::ERR_CONNECTION_REFUSED
webpack:///./src/interceptors.ts?:46 GOT MALFORMED HTTP REJECTION?? This shouldn't happen!
responseRejected @ webpack:///./src/interceptors.ts?:46
webpack:///./~/farmbot-toastr/dist/index.js?:136 Please try refreshing the page.
exports.warning @ webpack:///./~/farmbot-toastr/dist/index.js?:136
localhost:3000/api/sequences/ Failed to load resource: net::ERR_CONNECTION_REFUSED
webpack:///./src/interceptors.ts?:46 GOT MALFORMED HTTP REJECTION?? This shouldn't happen!
responseRejected @ webpack:///./src/interceptors.ts?:46
webpack:///./~/farmbot-toastr/dist/index.js?:136 Please try refreshing the page.
exports.warning @ webpack:///./~/farmbot-toastr/dist/index.js?:136
localhost:3000/api/tools/ Failed to load resource: net::ERR_CONNECTION_REFUSED
webpack:///./src/interceptors.ts?:46 GOT MALFORMED HTTP REJECTION?? This shouldn't happen!
responseRejected @ webpack:///./src/interceptors.ts?:46
webpack:///./~/farmbot-toastr/dist/index.js?:136 Please try refreshing the page.
exports.warning @ webpack:///./~/farmbot-toastr/dist/index.js?:136
VM555:37 WebSocket connection to 'ws://192.168.1.215:3002/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
WrappedWebSocket @ VM555:37
WebSocketStream @ stream.js:43
buildBuilderBrowser @ ws.js:78
wrapper @ index.js:129
MqttClient._setupStream @ client.js:228
MqttClient._reconnect @ client.js:556
(anonymous) @ client.js:571

**Comment by Arduns** [comment]
@RickCarlino  sorry but i don‘t know how to fix it， because i use the noemail？

**Comment by RickCarlino** [comment]
@Arduns Are you still having this issue? What error do you see now if so?

**Comment by Arduns** [comment]
@RickCarlino  the new version is fix this thanks
